version: '3.8'
services:
  mongo:
    image: mongo:jammy
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: graphQL_db
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local